/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToHome: typeof import('./src/components/BackToHome.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    Default: typeof import('./src/layouts/default.vue')['default']
    DefineInput: typeof import('./src/components/DefineInput.vue')['default']
    Dependents: typeof import('./src/components/Dependents.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElectronApi: typeof import('./src/components/demos/ElectronApi.vue')['default']
    ElementPlusProvider: typeof import('./src/components/ElementPlusProvider.vue')['default']
    Examples: typeof import('./src/components/Examples.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./src/components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NotivueProvider: typeof import('./src/components/NotivueProvider.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutConfigProvider: typeof import('@nutui/nutui')['ConfigProvider']
    NutProvider: typeof import('./src/components/NutProvider.vue')['default']
    PButton: typeof import('primevue/button')['default']
    RouterEntry: typeof import('./src/components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./src/components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./src/components/ToggleLanguage.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VantProvider: typeof import('./src/components/VantProvider.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VDefaultsProvider: typeof import('vuetify/components')['VDefaultsProvider']
    VDialog: typeof import('vuetify/components')['VDialog']
    VLocaleProvider: typeof import('vuetify/components')['VLocaleProvider']
    VThemeProvider: typeof import('vuetify/components')['VThemeProvider']
    Vue3_3Demo: typeof import('./src/components/Vue3_3Demo.vue')['default']
    VuetifyProvider: typeof import('./src/components/VuetifyProvider.vue')['default']
    VueUseMotion: typeof import('./src/components/VueUseMotion.vue')['default']
  }
}
