/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackToHome: typeof import('./../components/BackToHome.vue')['default']
    DarkModeToggle: typeof import('./../components/DarkModeToggle.vue')['default']
    Default: typeof import('./../layouts/default.vue')['default']
    DefaultMenu: typeof import('./../components/DefaultMenu.vue')['default']
    DefineInput: typeof import('./../components/DefineInput.vue')['default']
    Dependents: typeof import('./../components/Dependents.vue')['default']
    Examples: typeof import('./../components/Examples.vue')['default']
    Hello: typeof import('./../components/Hello.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    NaiveProvider: typeof import('./../components/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    RouterEntry: typeof import('./../components/RouterEntry.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    ToggleDarkMode: typeof import('./../components/ToggleDarkMode.vue')['default']
    ToggleLanguage: typeof import('./../components/ToggleLanguage.vue')['default']
    VBtn: typeof import('vuetify/components')['VBtn']
    VCard: typeof import('vuetify/components')['VCard']
    VCardActions: typeof import('vuetify/components')['VCardActions']
    VCardText: typeof import('vuetify/components')['VCardText']
    VDialog: typeof import('vuetify/components')['VDialog']
    VuetiyProvider: typeof import('./../components/VuetiyProvider.vue')['default']
    VueUseMotion: typeof import('./../components/VueUseMotion.vue')['default']
  }
}
